### ISSUE TITLE
Compile and install Voreen

### ISSUE THREAD

**Issue by PengchengShi1220** [jqmcginnis/voreen_tools#1]
Hi @jqmcginnis, I compile and install voreen according to the steps, but I have the following.
![111](https://user-images.githubusercontent.com/34006160/175801576-2221f6cc-9f24-4c1d-924f-ab421201b11e.PNG)
Could you please tell me how to resolve it? Thanks a lot!

**Comment by jqmcginnis** [comment]
Hello @spc819,

thank you very much for the interest in this repository. This repository is intended to provide some useful utility scripts to facilitate the generation for graphs in pyg. Of course I can also try to provide some help for the installation of voreen, but I would like to add that I am not a part of the development of the tool and also don't want to take any credit for this incredibly helpful software as I am not involved in its development.

Can you share details regarding your OS and the settings you have chosen to use for the installation? Does ccmake configuration work? :)

Alternatively, the voreen tool developers support you via: https://www.uni-muenster.de/Voreen/contact/index.html

Thanks again,

Julian

**Comment by PengchengShi1220** [comment]
Hello @jqmcginnis, thanks very much for your reply! I have installed voreen after deleting the /usr/local/lib/libpython3.9a file and recompiling voreen. Thanks again!

**Comment by jqmcginnis** [comment]
Hi @spc819,

feel free to re-open this issue (or another one) in case you run into any problems. 

Thank you,
Julian
